
MEMBER_STATUS_ACTIVE = 1
MEMBER_STATUS_INACTIVE = 0

OTP_STATUS_ACTIVE = 1
OTP_STATUS_USED = 2
OTP_STATUS_EXPIRED = 0

OTP_FOR_SIGNUP = 1
OTP_FOR_LOGIN = 2
OTP_FOR_PASSWORD_RESET = 3

OTP_TYPE_SMS = 1
OTP_TYPE_WHATSAPP = 2
OTP_TYPE_EMAIL = 3

LOGIN_TYPE_PASSWORD = 1
LOGIN_TYPE_OTP = 2